### ISSUE TITLE
Unable to resolve module `buffer

### ISSUE THREAD

**Issue by kevinleeTCA** [chitezh/react-native-swiper-animated#5] opened 2017-06-13 00:30 UTC
Hello,
Just hooked up a raw react-native project and try to use this fancy animation.
After install `react-native-swiper-animated` using `npm`
Try to run the example code.
But always got a problem:
```
bundling: UnableToResolveError: Unable to resolve module `buffer` from `/Users/kevinlee/trunk_souceTree/ReactMobile/node_modules/randombytes/node_modules/safe-buffer/index.js`: Module does not exist in the module map or in these directories:
  /Users/kevinlee/trunk_souceTree/ReactMobile/node_modules/randombytes/node_modules
,   /Users/kevinlee/trunk_souceTree/ReactMobile/node_modules
,   /Users/kevinlee/trunk_souceTree/node_modules
```
Tried all the methods suggested like

>  1. Clear watchman watches: `watchman watch-del-all`.
>   2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
>   3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

Still got this problem, and can not run successfully.

**Comment by chitezh** [comment] 2017-06-13 09:58
Thanks @kevinleeTCA 

That's a weird behaviour 
Could provide more information on the following?
a. react-native version
b. react version
c.  react-native-swiper-animated
d. a shot of your package.json showing the dependencies

Once I have the information, I'll try to reproduce.

Best
Kingsley

**Comment by eddie51405** [comment] 2017-06-14 13:24
Hi, I also got the same error right now. Could you please give me a help?
<img width="454" alt="2017-06-14 9 21 56" src="https://user-images.githubusercontent.com/27998409/27134386-f92ec810-5147-11e7-8fe0-5fccc10ee7df.png">

**Comment by chitezh** [comment] 2017-06-14 13:53
Thanks, let me see
Could be a problem with RN@0.44+

**Comment by eddie51405** [comment] 2017-06-14 14:53
Do you mean the problem is caused by react navigation?
How can I solve it?

**Comment by chitezh** [comment] 2017-06-14 16:15
No, I mean it might be a problem with the react native version. Never mind, I should be able to look at it now

**Comment by chitezh** [comment] 2017-06-14 16:26
@eddie51405 I just tried replicating the error but couldn't. Can I get a shot of the error?

**Comment by chitezh** [comment] 2017-06-14 17:02
The problem is likely from a dependency `react-native-uuid` which depends on `randombytes`. I think we can do without `react-native-uuid`

**Comment by chitezh** [comment] 2017-06-14 17:21
@kevinleeTCA @eddie51405 Please, upgrade to version `1.2.5` and let me know if it's fixed

**Comment by eddie51405** [comment] 2017-06-15 03:00
It can work right now! Thank you very much.

I want to do something when in the function onRightSwipe such as this:
onRightSwipe={() => {  console.log('right');  }} , but this seems no work.
How can I fix it?

**Comment by chitezh** [comment] 2017-06-15 07:13
I just noticed that `onRightSwipe` only works with `non-stack` swiping. Kindly remove the `stack`prop and try again

I'm closing this issue as the original complaint has been resolved. I'm more than happy to continue this discussion in a separate thread.z

**Comment by eddie51405** [comment] 2017-06-15 07:21
OK. Thank you very much!
I really like your package.

**Closed as completed** 2017-06-15 07:22 UTC
